Repository ongov/ckanext-ontario_theme, pull requests merged in 2023-09, with the labels that each got.

#405 [Bug]: Fixes missing tooltip on file size abbreviation
  ckanext/ontario_theme/fanstatic/common.css
Labels: 2.1.8

#397 fixed scripts w/solr8 ckan core
  config/solr/lang/contractions_fr.txt
  config/solr/lang/stopwords_fr.txt
  config/solr/protwords.txt
  config/solr/solrconfig.xml
  config/solr/stopwords.txt
  config/solr/synonyms.txt
  scripts/setup_solr.sh
Labels: 2.1.8

#407 [Task]: Show more button functionality
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/fanstatic/scripts/odc-show-more.js
  ckanext/ontario_theme/fanstatic/scripts/webassets.yml
  ckanext/ontario_theme/plugin.py
  ckanext/ontario_theme/templates/internal/snippets/facet_list.html
Labels: 2.1.8

#408 [Task]:Artificial intelligence content updates
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
  ckanext/ontario_theme/templates/internal/package/read.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
  ckanext/ontario_theme/templates/internal/snippets/facet_list.html
  ckanext/ontario_theme/templates/internal/snippets/package_item.html
Labels: 2.1.8

#409 [Task]: Schema Markup
  ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
  ckanext/ontario_theme/templates/external/scheming/package/read.html
  ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html
  ckanext/ontario_theme/templates/internal/package/read.html
  ckanext/ontario_theme/templates/internal/package/read_base.html
  ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
  ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
  ckanext/ontario_theme/templates/internal/page.html
  ckanext/ontario_theme/templates/internal/scheming/display_snippets/fluent_tags.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
  ckanext/ontario_theme/templates/internal/snippets/license.html
  ckanext/ontario_theme/templates/internal/snippets/organization.html
Labels: 2.1.8

#410 [Fix]: AI content updates
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
  ckanext/ontario_theme/templates/internal/package/read.html
Labels: bug, 2.1.8

#413 [Task]: Removes algorithm/ai label from dataset search page
  ckanext/ontario_theme/templates/internal/snippets/package_item.html
Labels: 2.1.9

#412 [Task]: update feedback form links
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/external/header.html
  ckanext/ontario_theme/templates/external/home/snippets/about_text.html
  ckanext/ontario_theme/templates/external/home/snippets/ontario_theme_contact_us.html
Labels: 2.1.9

#415 [Task]: AI and COVID-19 group pages minor markup fixes
  ckanext/ontario_theme/templates/internal/scheming/group/about.html
Labels: 2.1.9
