Repository ongov/ckanext-ontario_theme, pull requests merged in 2023-10, with the labels that each got.

#417 [Task]: About and Help page major changes
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/fanstatic/external/ontario_theme.css
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/external/home/help.html
  ckanext/ontario_theme/templates/external/home/snippets/about_text.html
  ckanext/ontario_theme/templates/internal/home/about.html
  ckanext/ontario_theme/templates/internal/page.html
Labels: 2.1.9

#418 [Task]: Minor ministries page fixes
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/fanstatic/external/ontario_theme.css
  ckanext/ontario_theme/public/images/ontario-icon-chevron-right.svg
  ckanext/ontario_theme/templates/external/home/help.html
  ckanext/ontario_theme/templates/internal/group/edit.html
  ckanext/ontario_theme/templates/internal/group/edit_base.html
  ckanext/ontario_theme/templates/internal/group/index.html
  ckanext/ontario_theme/templates/internal/group/read.html
  ckanext/ontario_theme/templates/internal/group/read_base.html
  ckanext/ontario_theme/templates/internal/header.html
  ckanext/ontario_theme/templates/internal/home/about.html
  ckanext/ontario_theme/templates/internal/organization/edit.html
  ckanext/ontario_theme/templates/internal/organization/edit_base.html
  ckanext/ontario_theme/templates/internal/organization/index.html
  ckanext/ontario_theme/templates/internal/organization/new.html
  ckanext/ontario_theme/templates/internal/organization/read.html
  ckanext/ontario_theme/templates/internal/organization/read_base.html
  ckanext/ontario_theme/templates/internal/organization/snippets/organization_item.html
  ckanext/ontario_theme/templates/internal/package/base.html
  ckanext/ontario_theme/templates/internal/package/edit_base.html
  ckanext/ontario_theme/templates/internal/package/new_resource.html
  ckanext/ontario_theme/templates/internal/package/new_resource_not_draft.html
  ckanext/ontario_theme/templates/internal/package/resource_edit_base.html
  ckanext/ontario_theme/templates/internal/package/resource_read.html
  ckanext/ontario_theme/templates/internal/package/search.html
  ckanext/ontario_theme/templates/internal/package/snippets/package_base_breadcrumb.html
  ckanext/ontario_theme/templates/internal/page.html
  ckanext/ontario_theme/templates/internal/snippets/search_form.html
Labels: 2.1.9

#419 [Task]: Add missing nav role and aria labels to current page
  ckanext/ontario_theme/fanstatic/scripts/odc-active-page.js
  ckanext/ontario_theme/fanstatic/scripts/webassets.yml
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/internal/header.html
Labels: 2.1.9

#427 Change back homepage banner to 'contact us'
  ckanext/ontario_theme/templates/internal/home/layout3.html
Labels: 2.1.9

#428 Ckanext validation: remove schema upload UI component
  ckanext/ontario_theme/plugin.py
  ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
  ckanext/ontario_theme/templates/internal/datastore/dictionary.html
  ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
Labels: ckanext_validation

#422 [Task]: Add description lists to About page content
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/external/home/snippets/about_text.html
Labels: 2.1.10

#434 [Task]: Remove the RSS box from the Dataset page
  ckanext/ontario_theme/templates/internal/package/read_base.html
Labels: 2.1.10

#435 [Task]: Hide Supporting Files heading when there are no supporting files
  ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
Labels: 2.1.10

#433 Redesign the access level & AI callout boxes
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/templates/external/package/snippets/ontario_theme_access_level.html
  ckanext/ontario_theme/templates/internal/package/read.html
  ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
Labels: 2.1.10

#421 [Task]: group page minor fixes
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/internal/group/snippets/group_item.html
  ckanext/ontario_theme/templates/internal/group/snippets/group_list.html
Labels: 2.1.10

#431 [Task]: Remove truncation for the dataset & dataset resource names
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
  ckanext/ontario_theme/templates/internal/snippets/package_item.html
  ckanext/ontario_theme/templates/internal/snippets/package_list.html
Labels: 2.1.10

#432 [Task]: Align the pagination colors with the design system recomended colors
  ckanext/ontario_theme/fanstatic/common.css
Labels: 2.1.10
