Repository ongov/ckanext-ontario_theme, pull requests merged in 2023-08, with the labels that each got.

#369 Implementing Design System dropdown and label
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/public/images/ontario-material-dropdown-arrow-48px.svg
  ckanext/ontario_theme/templates/internal/group/index.html
  ckanext/ontario_theme/templates/internal/group/read.html
  ckanext/ontario_theme/templates/internal/organization/index.html
  ckanext/ontario_theme/templates/internal/organization/read.html
  ckanext/ontario_theme/templates/internal/organization/read_base.html
  ckanext/ontario_theme/templates/internal/package/search.html
  ckanext/ontario_theme/templates/internal/snippets/search_form.html
Labels: 2.1.5

#226 Script to install ckan locally in dev and prod modes
  .gitignore
  config/README.md
  config/ckan/ckan.ini
  config/gtm/gtm.html
  config/gtm/gtm_ns.html
  config/nginx/local_ckan
  config/nginx/local_ckan_ssl
  config/supervisor/ckan-uwsgi.conf
  config/supervisor/ckan-worker.conf
  scripts/README.md
  scripts/helper_functions.sh
  scripts/setup_ckan_local.sh
  scripts/setup_postgres_local.sh
Labels: 2.1.5

#387 Fixes link touching label
  ckanext/ontario_theme/fanstatic/common.css
Labels: 2.1.5

#388 Fix branch switch with local ontario_theme setup
  scripts/setup_ckan_local.sh
Labels: 2.1.5

#394 Fixes ministry activity stream from overlapping with heading
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/templates/internal/organization/activity_stream.html
  ckanext/ontario_theme/templates/internal/organization/index.html
  ckanext/ontario_theme/templates/internal/organization/read_base.html
  ckanext/ontario_theme/templates/internal/package/search.html
  ckanext/ontario_theme/templates/internal/page.html
  ckanext/ontario_theme/templates/internal/scheming/organization/about.html
Labels: 2.1.6

#400 Task: Switches show more to a tertiary button
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/templates/internal/snippets/facet_list.html
Labels: 2.1.7

#390 Data-1131 add required data types
  ckanext/ontario_theme/templates/internal/datastore/snippets/dictionary_form.html
Labels: 2.1.7
