Repository ongov/ckanext-ontario_theme, pull requests merged in 2024-01, with the labels that each got.

#465 [Fix]: Changes to spelling of French "Search" aria-label
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
Labels: 2.1.12

#455 [Task]: Adopt ld+json for dataset schema.org tags
  ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
  ckanext/ontario_theme/templates/external/scheming/package/read.html
  ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html
  ckanext/ontario_theme/templates/internal/package/read.html
  ckanext/ontario_theme/templates/internal/package/read_base.html
  ckanext/ontario_theme/templates/internal/package/snippets/resource_item.html
  ckanext/ontario_theme/templates/internal/package/snippets/resources_list.html
  ckanext/ontario_theme/templates/internal/package/snippets/schema_markup.html
  ckanext/ontario_theme/templates/internal/page.html
  ckanext/ontario_theme/templates/internal/scheming/display_snippets/fluent_tags.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
  ckanext/ontario_theme/templates/internal/snippets/license.html
  ckanext/ontario_theme/templates/internal/snippets/organization.html
Labels: 2.1.12

#462 [Bug]: Object Identification using data attributes
  ckanext/ontario_theme/templates/internal/group/snippets/group_item.html
  ckanext/ontario_theme/templates/internal/organization/snippets/organization_item.html
Labels: 2.1.12

#463 [Task]: Update the tab labels on ministry and dataset pages
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/internal/group/activity_stream.html
  ckanext/ontario_theme/templates/internal/group/read_base.html
  ckanext/ontario_theme/templates/internal/organization/activity_stream.html
  ckanext/ontario_theme/templates/internal/organization/read_base.html
  ckanext/ontario_theme/templates/internal/package/activity.html
  ckanext/ontario_theme/templates/internal/package/read.html
Labels: 2.1.12

#464 [Bug]: French sorting for datasets does not lead to correct results
  ckanext/ontario_theme/plugin.py
  ckanext/ontario_theme/templates/internal/group/read.html
  ckanext/ontario_theme/templates/internal/organization/read.html
  ckanext/ontario_theme/templates/internal/package/search.html
  ckanext/ontario_theme/templates/internal/snippets/package_list.html
  config/solr/managed-schema
  config/solr/solrconfig.xml
Labels: 2.1.12

#467 [Task]: change Addtional Information table from <table> to <div>s
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html
  ckanext/ontario_theme/templates/internal/package/snippets/additional_info.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
Labels: 2.1.13

#473 [Task]: Add a ckan validator to trim whitespace from EN and FR titles
  ckanext/ontario_theme/plugin.py
  ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
  ckanext/ontario_theme/validators.py
Labels: 2.1.13

#471 [Hotfix]: Dataset 500 error
  ckanext/ontario_theme/plugin.py
Labels: 2.1.13

#349 Condition to prevent Nonetype concatenate error
  ckanext/ontario_theme/templates/internal/snippets/search_form.html
Labels: 2.1.14

#474 [Bug]: Sorting on Ministries is not implemented
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/organization.py
  ckanext/ontario_theme/plugin.py
  ckanext/ontario_theme/templates/internal/organization/index.html
  requirements.txt
Labels: 2.1.14

#454 [Task]: Move the search facet "Access level" display as radio buttons
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/fanstatic/scripts/odc-access-level.js
  ckanext/ontario_theme/fanstatic/scripts/webassets.yml
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/plugin.py
  ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
  ckanext/ontario_theme/templates/internal/snippets/access_level_radio_buttons.html
  ckanext/ontario_theme/templates/internal/snippets/facet_arrangement.html
  ckanext/ontario_theme/templates/internal/snippets/search_form.html
Labels: 2.1.14

#502 [Task]: Additional info table headers removed and added description lists
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/templates/external/scheming/package/snippets/additional_info.html
  ckanext/ontario_theme/templates/internal/package/snippets/additional_info.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
Labels: 2.1.15

#501 [Task]: Update ckan.ini to reflect organization item page limit
  config/ckan/ckan.ini
Labels: 2.1.15

#494 [Task]: Align styling of "Additional information" table in resource page to table in Dataset page
  ckanext/ontario_theme/fanstatic/common.css
Labels: 2.1.15

#496 [Task]: Add description meta tags to every page and remove og tags
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/external/home/help.html
  ckanext/ontario_theme/templates/external/home/snippets/ontario_theme_intro.html
  ckanext/ontario_theme/templates/internal/base.html
  ckanext/ontario_theme/templates/internal/group/index.html
  ckanext/ontario_theme/templates/internal/group/read_base.html
  ckanext/ontario_theme/templates/internal/home/about.html
  ckanext/ontario_theme/templates/internal/organization/index.html
  ckanext/ontario_theme/templates/internal/organization/read_base.html
  ckanext/ontario_theme/templates/internal/package/read_base.html
  ckanext/ontario_theme/templates/internal/package/search.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
Labels: 2.1.15

#503 [Task]: Help content changes
  ckanext/ontario_theme/fanstatic/common.css
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/external/package/snippets/ontario_theme_access_level.html
  ckanext/ontario_theme/templates/internal/snippets/package_item.html
  ckanext/ontario_theme/templates/internal/snippets/search_form.html
Labels: 2.1.15

#497 [Task]: Align Group page design and Ministry page design
  ckanext/ontario_theme/i18n/ckanext-ontario_theme.pot
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.po
  ckanext/ontario_theme/templates/internal/group/activity_stream.html
  ckanext/ontario_theme/templates/internal/group/read.html
  ckanext/ontario_theme/templates/internal/group/read_base.html
  ckanext/ontario_theme/templates/internal/group/snippets/info.html
  ckanext/ontario_theme/templates/internal/organization/read_base.html
  ckanext/ontario_theme/templates/internal/scheming/group/about.html
  ckanext/ontario_theme/templates/internal/scheming/organization/about.html
  ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
  ckanext/ontario_theme/templates/internal/snippets/group.html
Labels: 2.1.15

#504 [Task]: Change Change Other (Not Open) license to Not applicable
  ckanext/ontario_theme/i18n/fr/LC_MESSAGES/ckanext-ontario_theme.mo
  ckanext/ontario_theme/schemas/licences.json
Labels: 2.1.15
